title: Application Malaria Scorecard
logo: /assets/img/scorecard_logo.png
ownerlogo: /assets/img/pmi_logo.png
description: Bienvenu sur le site de l'application Malaria Scorecard.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal